[package]
name = "wildfire"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16"

[dependencies.bevy_life]
git = "https://github.com/ManevilleF/bevy_life"
rev = "d2f70049d3ffda496fd01ff12bbf29e7d11f115d"
features = ["auto-coloring"]
